### ISSUE TITLE
Subdirectory support

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/members.js#39]
Currently, if you try to use members.js on a site with a subdirectory, you get a error Failed to initialize error:

![members.js error](https://user-images.githubusercontent.com/101513/83891712-82f68f00-a745-11ea-8d4f-8d2bf508d6fa.png)

Members.js need to work with subdirectory sites please :)

**Comment by rishabhgrg** [comment]
@ErisDS Just some quick thoughts on the missing subdirectory support bug [here](https://github.com/TryGhost/members.js/issues/39), seems like this one will be a bit tricky to support directly without any kind of input from the theme dev, as we'll need to guess whats the correct path for Ghost site from the URL. 😬 Definitely a use-case I missed initially when we decided to go with considering `window.location.origin` as the default site url and get rid of init.

One way I can think to solve this without any init step or user input is by just iterating over the URL path if the Ghost API on original path - `window.location.origin` - fails , which should in most cases just work with the first path in URL. 

So in case the subDir setup is `http://mysite.com/blog` and the user is on - `http://mysite.com/blog/something/test-post/`, the script attempts to load Ghost API as

http://mysite.com/members/api/site ✖️ 
⬇️ 
http://mysite.com/blog/members/api/site ✔️ 
⬇️ 
Initialize

Definitely not ideal and has holes like similar setup on root path, will think of more options as well with fresh 🧠

**Comment by ErisDS** [comment]
2 other options:

script does need minimal config block (not ideal)
output a meta tag with this information in ghost_head
I think the latter is probably correct, something like:

e.g. <meta name="members:api" value="https://mysite.com/blog/members/api">


Need to think on it though - TBC

**Comment by rishabhgrg** [comment]
Definitely like the latter direction, ideally the only root/absolute input we need for members script is the site URL or members root, which then allows loading all the other information needed to initialize the script, and injecting that through `ghost_head` will work nicely.

**Comment by rishabhgrg** [comment]
@ErisDS Want to get a sense-check on the final approach here. So adding a new meta tag in `ghost_head` which has the value of ghost site URL seems like the right approach to me in this case, as thats the kind of information that does make sense in meta tag for any ghost site and is definitely not something we should consider asking to be configured manually for script. Was thinking of inserting meta tag as -

```
<meta name="ghost:site" content='https://mysite.com/blog' />
```

The reason to go with `siteUrl` instead of a members specific endpoint is because the `siteUrl` is the minimum value atm which the script needs to know to work through all other values including members/admin API endpoints, so it didn't make sense to extend it to something more specific for now. Also, `ghost:site` seems like a useful information in general to output on theme and don't think has any other side-effects. 

Have already done change for this quickly [here](https://github.com/TryGhost/Ghost/compare/master...rishabhgrg:ghost-site-meta?expand=1) and tested with members.js, works nicely. 

- It could be also that this meta tag is output irrespective of members enabled, though not needed anywhere else atm, just a thought.

- The naming for meta name is ofc up for discussion, other thoughts I had was `ghost:url` or `ghost:site:url`, but former seems to be a bit less explicit that its site url, and latter a bit too explicit, which is why `ghost:site` makes sense to me.

Lmk if this makes sense or if you have any other thoughts on naming/approach/alternatives :)

**Comment by ErisDS** [comment]
Yeah I think this is good for now, it all def needs proper review next week when we're working on members settings, but for now this solves the problem really simply :)
