### ISSUE TITLE
Initialise base URL via data attribute

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/members.js#54]
This is a revisit of https://github.com/TryGhost/members.js/issues/39. 

**Problem**: 
Subdirectory support is fixed, but on reflection the solution isn't the simplest one!

**Appetite**:
30mins? 😂 
Seriously: 1/2 day

**Solution**

Currently we output a meta tag:

```
const siteUrl = urlUtils.getSiteUrl().replace(/\/$/, '');

<meta name="ghost:site" content='${siteUrl}' />
<script defer src="https://unpkg.com/@tryghost/members-js@latest/umd/members.min.js"></script>
```

There's no real need for a whole extra tag... we should instead keep it simple with a data attribute:

```
<script defer src="https://unpkg.com/@tryghost/members-js@latest/umd/members.min.js" data-ghost="${urlUtils.getSiteUrl()}"></script>
```

Notes:

- We should not strip the trialing slash from the URL - our pattern is always to assume it exists?
- Attributes should always use double quotes

**Comment by rishabhgrg** [comment]
😅 Haha yeah thats definitely a shorter route to achieve this. 

@ErisDS Any reason the data attribute shouldn't be `data-ghost-site-url` instead of `data-ghost` ? My preference for former is just to be more explicit what the attribute is than a bit more generic `data-ghost`.

> We should not strip the trialing slash from the URL - our pattern is always to assume it exists?

👍 Yeah, also from members.js perspective either shouldn't make difference as it takes care of both case

**Comment by ErisDS** [comment]
> @ErisDS Any reason the data attribute shouldn't be data-ghost-site-url instead of data-ghost ? My preference for former is just to be more explicit what the attribute is than a bit more generic data-ghost.

because this is what @JohnONolan said 😬
