### ISSUE TITLE
Account page broken after changing account details

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/members.js#87]
**To reproduce**

1. open the account page on the frontend
2. click on "Edit" in the name/email row to change the account info details
3. edit the name and hit "Save"

**Result:** the user is redirected to the account main screen (expected), but the screen is broken, looks like all the data is lost.

<img width="510" alt="Screenshot 2020-08-19 at 16 06 17" src="https://user-images.githubusercontent.com/353959/90645540-575c4e80-e236-11ea-9cd5-e03a2cae2efe.png">

**Expected:** the user should be redirected to the account main screen and should see the data being correctly updated.

**Comment by rishabhgrg** [comment]
@peterzimon Yeah can reproduce, its happening because of incomplete response of save API which overwrites the existing data locally, the data is not lost in DB though and correctly saved since refresh of screen shows correct updated data. Will take a look at fixing the API result if possible to make it consistent again,  otherwise update the local check. :)
